@startuml

class HomeStem{

}
abstract Device{
  +init()
}
abstract InputDevice{
  +retrieve()
}
abstract Sensor{
  #sense()
}
class HygrothermoSensor{
  #sense()
}

HomeStem o-- InputDevice : collect <
Device <|-- InputDevice
InputDevice <|-- Sensor
Sensor <|-- HygrothermoSensor
' abstract Device{
'   +connect()
' }

' abstract InputDevice{
'   +retrieve()
' }

@enduml