version: "3.7"
services:
  doc:
    image: home-stem-doc
    build: .
    restart: always
    working_dir: /doc
    volumes:
      - .:/doc:cached
      - /doc/node_modules
    ports:
      - "4100:4000"
